remote_theme: tocttou/hacker-blog
plugins:
- jekyll-remote-theme

title: Minimal JS Image Classifiers
description: Some basic examples of client interfaces to a computer vision API

author:
  name: Jeremy Howard
